version: '3.9'

services:
  app:
    build: .
    container_name: wb_price_bot
    restart: always
    volumes:
      - ./bot/bot.log:/wb_price_bot/bot.log
      - ./bot/data/wildberries.db:/wb_price_bot/data/wildberries.db
    env_file:
      - .env
